name: Build/release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@master
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@master
        with:
          node-version: 14
      - name: Build/release Electron app
        uses: michalzaq12/action-electron-nuxt@v1
        with:
          github_token: ${{ secrets.github_token }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
