name: Build/release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@master
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@master
        with:
          node-version: 14
      - name: Build and sign Electron app
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_LINK: ${{ secrets.CERTIFICATE_WINDOWS_PFX }}
          CSC_KEY_PASSWORD: ${{ secrets.CERT_PASSWORD }}
        run: |
          cp src/renderer/.env.prod src/renderer/.env
          yarn
          yarn build
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          files: |
            build/weview-sync-tool.exe
            build/latest.yml
            build/weview-sync-tool.exe.blockmap
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
